### ISSUE TITLE
Limitations long-term 

### ISSUE THREAD

**Issue by ShalokShalom** [tshort/StaticCompiler.jl#140]
Hi, and thanks :)

Is this considered to be limited as of now forever, or is it planned, to lift the [listed](https://github.com/tshort/StaticCompiler.jl#limitations) limitations long term?

I assume some are more difficult to tackle than others, do you think it is sensible to open up issues on every one of them?

I would link those issues then, in the section of the README, that currently lists them. 

P.S: This is a wonderful package, and I love to use this to compile Julia to [lunatic.solutions](lunatic.solutions) 😉 

Thanks a lot

**Comment by brenhinkeller** [comment]
This is a good question. Linking to libjulia is definitely still a long-term goal, as are other methods for working around some of these limitations – though at the same time, the solution for general static compilation of Julia code may eventually take a different form than this package (and may be either part of or more deeply integrated with Julia itself,  in which case this package might stick more to its current scope)

**Comment by ShalokShalom** [comment]
I consider this uncertainty worth to open several issues, that all track individual aspects of this task. So we can track this, and other projects with the same goal can study it. What is not documented, might as well not exist. Maybe with a special label?

**Comment by ShalokShalom** [comment]
@MasonProtter 

Thanks a lot. Could you show me, where this has been solved?

**Comment by MasonProtter** [comment]
@ShalokShalom no I just hit the `close` button and it defaulted to "closed as completed" which is annoying. I just closed the issue because there isn't any issue to track in here, it's a mix of questions, and a incomplete duplicate of https://github.com/tshort/StaticCompiler.jl/issues/59

It seems the only options are "close as completed" and "Close as not planned" and neither of those are great descriptors, but I'll switch it to "not planned". 

For questions and discussion part of the post though, we should open a Discussions section in the repo @tshort, I don't have permissions to do that, would you be able to? It's in the repo-settings.

**Comment by tshort** [comment]
I enabled discussions (I think).
